"""autogenerated by genpy from zuros_control/motorMSG.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motorMSG(genpy.Message):
  _md5sum = "a2a9eec3fd2b159cc6afa5290066e5df"
  _type = "zuros_control/motorMSG"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#left motor
int32 left_accel
int32 left_speed

#right motor
int32 right_accel
int32 right_speed

"""
  __slots__ = ['left_accel','left_speed','right_accel','right_speed']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_accel,left_speed,right_accel,right_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motorMSG, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_accel is None:
        self.left_accel = 0
      if self.left_speed is None:
        self.left_speed = 0
      if self.right_accel is None:
        self.right_accel = 0
      if self.right_speed is None:
        self.right_speed = 0
    else:
      self.left_accel = 0
      self.left_speed = 0
      self.right_accel = 0
      self.right_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.left_accel, _x.left_speed, _x.right_accel, _x.right_speed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_accel, _x.left_speed, _x.right_accel, _x.right_speed,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.left_accel, _x.left_speed, _x.right_accel, _x.right_speed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_accel, _x.left_speed, _x.right_accel, _x.right_speed,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
